- name: Setup HLS streamer with nginx and Let's Encrypt
  hosts: webservers
  become: true
  gather_facts: false

  pre_tasks:
    - name: Install python3 if missing
      raw: |
        apt-get update -qq && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y python3
      changed_when: false
      ignore_errors: true

    - name: Gather facts (now that Python is installed)
      setup:

    - name: Ensure remote_tmp dir exists with correct permissions
      file:
        path: /root/.ansible/tmp
        state: directory
        mode: "0700"
        owner: root
        group: root

  roles:
    - hls_streamer
