- name: Install certbot
  apt:
    name: certbot
    state: present

- name: Create webroot directory
  file:
    path: "{{ webroot_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Deploy global nginx config for HTTP ACME challenge
  template:
    src: nginx-default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
  notify: Reload nginx

- name: Ensure nginx is reloaded before certbot
  meta: flush_handlers

- name: Obtain Let's Encrypt certificate
  command: >
    certbot certonly --webroot
    --webroot-path {{ webroot_path }}
    --non-interactive
    --agree-tos
    --email {{ email }}
    -d {{ domain_name }}
  args:
    creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
